name: Smoke Tests - PR

on: [push]
jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Firefox
        run: |
          sudo apt-get update
          sudo apt-get install firefox

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=firefox

      - name: Gerar relatório
        run: mvn cluecumber-report:reporting
