name: Smoke Tests - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribuition: 'corretto'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Instalar o Chromedriver
        uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Navegar para pasta do projeto
        run: cd site-ecommerce-curso-selenium
        
      - name: Run tests
        run: mvn test -Dtest=**/*RunCucumberTest -Dbrowser=chrome
