name: Sample Tests - Push

on:
  push:
    branches:
      - main

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Instalar Dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          mvn -B clean verify

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=firefox

      - name: Gerar relatório
        run: mvn cluecumber-report:reporting
